config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :moods, only: [:index]
  resources :teachers, only: [:index] do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index, :edit, :update, :destroy]

  resources :exercices, only: [:index, :show] do
    resources :achievements, only: [:create, :new]
  end
  resources :achievements, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/achievement.rb
class Achievement < ApplicationRecord
  belongs_to :user
  belongs_to :exercice
  belongs_to :mood

  validates :date, presence: true
  validates :rating, inclusion: { in: 0..5 }, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :teacher
end

app/models/exercice.rb
class exercise < ApplicationRecord
  belongs_to :mood
  # validates :name, presence: true
end

app/models/mood.rb
class Mood < ApplicationRecord
  has_many :exercices
  has_many :achievements
  # validates :name, presence: true, uniqueness: true
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :bookings
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :achievements, dependent: :destroy
  has_many :bookings
  #validates :first_name, presence: true
  #validates :last_name, presence: true
end

app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController

  def new
    @exercice = Exercice.find(params[:exercice_id])
    @achievement = Achievement.new
  end

  def index
    @achievements = current_user.achievements.sort_by{|achievement| achievement.date}
    gon.userAchivementsRatings = []
    gon.userAchivementsDates = []
    @achievements.each do |achievement|
      gon.userAchivementsRatings << achievement.rating
      gon.userAchivementsDates << achievement.date.strftime("%e/%m/%Y")
    end
  end

  def create
    @achievement = Achievement.new(set_params)
    @achievement.user = current_user
    @exercice = Exercice.find(params[:exercice_id])
    @achievement.exercice = @exercice
    @achievement.mood = @exercice.mood
    @achievement.date = Time.now
    if @achievement.save!
      redirect_to achievements_path
    else
      redirect_to exercice_path(@exercice)
    end
  end

  private

  def set_params
    params.require(:achievement).permit(:rating)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.where(user: current_user)
  end

  def new
    @teacher = Teacher.find(params[:teacher_id])
    @booking = Booking.new
  end

  def create
    @teacher = Teacher.find(params[:teacher_id])
    @booking = Booking.new(set_booking_params)
    @booking.teacher = @teacher
    @booking.date = Time.now
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path(@teacher)
    else render :new
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(set_booking_params)
    redirect_to bookings_path
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def set_booking_params
    params.require(:booking).permit(:title, :teacher_id, :date)
  end
end

app/controllers/exercices_controller.rb
class ExercicesController < ApplicationController
  def index
    search = params["search"]
    if search.present?
      name = search["name"]
      @exercices = Exercice.ransack(name_or_description_cont: name).result
    else
      @exercices = Exercice.all
    end
  end

  def show
    @remove_btn = (params[:remove_btn] == "true")
    @exercices = Exercice.all
    @exercice = Exercice.find(params[:id])
    @achievement = Achievement.new
    @mood = @exercice.mood
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  def index
    @exercises = Exercise.all
  end

  def show
    @exercise = Exercise.find(params[:id])
  end
end

app/controllers/moods_controller.rb
class MoodsController < ApplicationController
  def index
    @moods = Mood.all
    @exercices = Exercice.all
  end

  def find
    @mood = Mood.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  def home
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
    # @teachers = Teacher.all
    @teachers = Teacher.where.not(latitude: nil, longitude: nil)
    @booking = Booking.new()

    @markers = @teachers.map do |teacher|
      {
        lat: teacher.latitude,
        lng: teacher.longitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { teacher: teacher }),
        image_url: helpers.asset_url('mark2.jpg')
      }

    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # def select_exos(exercices, mood)
  #   exercices.select { |exercice| exercice.mood == mood }.sample
  # end

  def select_exos(mood)
    mood.exercices.sample
  end

  def select_another_exos(exercices, rejected_exo, mood)
    exercices_two = exercices.reject { |exo| exo == rejected_exo }
    exercices_two.select { |exercice| exercice.mood == mood }.sample
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/achievements/index.html.erb
<%= include_gon %>

<div class= "first-dash-container">
  <div class="first-dash-wrapper">
    <div class= "achievements-title-wrapper pt-5">
      <h1>Achievements</h1>
    </div>

    <div class= "dashboard-container">
      <p class= "scroll-title"> Your daily exercises </p>

      <div class="container-fluid mr-5 ml-5">
        <div class="row">
          <div class="col-4">
            <div class= "dash-wrapper-left">
              <% @achievements.reverse.each do | achievement | %>
                <div class="card-product">
                  <img src="https://i.pinimg.com/564x/8a/e0/b8/8ae0b80c16498671ec54914f284470c5.jpg">
                  <div class="card-product-infos">
                   <span class= "dashboard-list">
                    <p class= "dashboard-date"><strong><%= achievement.date.strftime("%e/%m/%Y")%></strong> </p>
                    <p class= "dashboard-phrase"><%= "Today you were #{achievement.mood.name}. During the time you took for yourself, you did a #{achievement.exercice.name} exercise. You now feel on a #{achievement.rating} level. Keep going that way to improve your mood !" %></p>
                    </span>
                  </div>
                </div>
              <% end %>
            </div>
          </div>

          <div class="col-8">
            <div class= "dashboard-wrapper-right">
              <div id="container" style="width: 950px; height: 550px; margin: 0 auto"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class= "exercises-link">
    <%= link_to "More time", exercices_path(@exercice), class: "btn-to-exercices" %>
  </div>
</div>

<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/series-label.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>

app/views/bookings/edit.html.erb
<h3 style="text-align: center;"> Want to update ?</h3>

<div style="margin-top: 32px;">
  <%= simple_form_for [@contract, @booking] do |f| %>
  <%= f.association :teacher%>
  <%= f.input :date, as: :date %>
  <%= f.button :submit, "Update", class: "btn-bouton-show" %>
<% end %>
</div>

app/views/bookings/index.html.erb
<div class="bookings-title pt-5" >
  <h1 >My Bookings</h1>
</div>

<div class="tyt-bookings">

  <% @bookings.each do |booking| %>

    <div class="booking-card">

      <img style="height: 100%;" src="https://i.pinimg.com/564x/8a/e0/b8/8ae0b80c16498671ec54914f284470c5.jpg">

      <p class="booking-card-description"> <%= "#{booking.user.first_name} your studio is #{booking.teacher.name},#{booking.teacher.address} and start on #{booking.date.strftime("%A %e %B")}."%></p>
        <%= link_to 'cancel', booking_path(booking),
          method: :delete,
          data: { confirm: "Are you sure?" },
        class: 'delete-b' %>

    </div>

  <% end %>

</div>

<%= link_to "Achievements", achievements_path, class: "achievement-link" %>

app/views/bookings/new.html.erb
<h1 class="classes-title pt-5"> Book your class !</h1>

<div class="general-new-bookings">
  <div class="new-booking">
      <%= simple_form_for [@teacher, @booking] do |f| %>
        <%= f.input :title, label: false%>
        <%= f.submit ' G O  ! ', class: "new-bookings-btn"%>
      <% end %>
  </div>
</div>

app/views/exercices/index.html.erb
<div class="general">

  <h1 class="pt-5">Exercises</h1>

  <div class="exo-form">
    <%= simple_form_for :search, method: "GET", html: { class: 'form-inline' } do |f| %>
      <%= f.input :name, label: false, input_html: {value: ""} %>
      <%= f.submit "Search", class: "search" %>
    <% end %>
  </div>

  <div class="container">
    <div class="row">
      <% @exercices.each do | exercice | %>

        <div class="col-lg-4 ">
          <%= link_to exercice_path(exercice) do %>
            <div class="tyt-card animated">
              <div class="card-category ">
                <%= exercice.name %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

</div>

app/views/exercices/show.html.erb
<div class="exercise-show-background">
  <div class="exercise-show-wrapper">
    <div class="exercise-show-title pt-5">
      <h1><%= @exercice.name %></h1>
    </div>

    <div class="exercise-show-global-content">
      <div class="left-button text-center">
        <p class="shuffle-text">If the exercise doesn't suits you,<br/> you can change once!</p>
        <div class="exercise-show-shuffle">
          <% unless @remove_btn %>
            <%= link_to 'Change', exercice_path(select_another_exos(@exercices,
              @exercice, @mood), remove_btn: true), class: "btn show-exercise-btn shuffle" %>
          <% else %>
            <div id="blank-shuffle"></div>
          <% end %>
        </div>
      </div>

      <div class="exercise-show-card-exercise text-center">
        <div class="image-box">
          <% if @exercice.description.present? %>
            <p class="exercice-description"><%= @exercice.description %></p>
          <% elsif @exercice.photo.present? %>
            <div class="image-exercise"> <%= image_tag((@exercice.photo), class: "mx-auto d-block")%></div>
          <% elsif @exercice.video.present? %>
            <iframe width="600" height="335" src="<%= @exercice.video %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          <% end %>
        </div>
      </div>

      <div class="right-button text-center">
        <button id="sweet-alert-demo" class="btn show-exercise-btn done">Done</button>
      </div>
    </div>

    <div class="exercise-show-review">
      <h2>How do you feel after your exercise?</h2>
      <div class="exercises-show-full-sliderbar">
        <%= simple_form_for [@exercice, @achievement] do |f| %>
        <div class="slidecontainer">
          <input type="range" min="0" max="5" value="0" class="slider" id="achievement_rating" name="achievement[rating]">
        </div>
        <h3 class="text-center" id='sliderFeedback'>Move the cursor according to your new mood !</h3>
      </div>
        <%= f.button :submit, "Done!", class: "d-none", id: "submit-button" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">
    <link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">



    <title>TakeYourTime.Stop for 15 minutes...</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/moods/index.html.erb
<div class="moods-index-background">

  <!-- <span class= "dollar">$</span> -->
  <div class= "mood-index-wrapper">
    <div class= "mood-index-title pt-4">
     <h1>How do you feel today ?</h1>
    </div>
    <div class= "moods-cards-wrapper px-5">
      <div class="container-fluid">
        <div class="row">
          <% @moods.each do | mood | %>
            <div class="col-lg-3">
              <%= link_to exercice_path(select_exos(mood)), class: "a" do %>
                <div class="d-flex justify-content-center w-100">
                  <div class="moods-card-category d-flex justify-content-center align-items-center animated">
                    <div><%= mood.name %></div>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="home-container">
  <div class="home-left">
    <div class="home-left-container">
      <div class="elements">
        <div class="card-home">
          <div class="card-body">
            <p class="card-title">Stop for 15 minutes and improve your life.</p>
            <p class="card-paragraphe"> "The biggest secret for happiness, is to be good with ourself." <br><i> - Bernard Fontenelle </i></p>
            <%= link_to "Start now", moods_path, class: "block btn home-btn" %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="home-right"></div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class= "tyt-navbar d-flex justify-content-between align-items-center">
  <%= link_to root_path do %>
    <div class="d-flex">
      <%#= image_tag "mon-image", class: "" %>
      <div class="<%= url_for == root_path ? 'white-color' : "logo-background" %>">TakeYourTime
      </div>
    </div>
  <% end %>
  <div class= "tyt-navbar-right">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag "anne-laure-small.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Follow your path", achievements_path, class: "dropdown-item" %>
            <%= link_to "Find a class", teachers_path, class: "dropdown-item" %>
            <%= link_to "Who are we ?", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/teachers/_infowindow.html.erb
<h6 style="font-family: 'pacifico', 'sans-serif';
font-weight: lighter;"> <%= teacher.name %> </h6>
<p> <%= teacher.address %> </p>

app/views/teachers/index.html.erb
<h1 class="teachers-title pt-5">My Classes</h1>

<div class="teacher-box">
  <div class="row">
    <div class="col-lg-6" >
      <div class="teacher-right"> <!--dash-wraper-->
        <% @teachers.each do |teacher| %>
          <div class="border" style='border: 1px solid gray;'> <!--card-product-->
            <%= image_tag("#{teacher.name}-photo.jpg") %>
            <p><%="Come practice at #{teacher.name}, located on the #{teacher.address}. The studio is offering #{teacher.description}!"%></p>

              <% @teacher = teacher %>
              <%# /teachers/:teacher_id/bookings %>
              <%= simple_form_for([@teacher, @booking], method: :post) do |f| %>
                <%= f.association :teacher, selected: params[:teacher_id], label: false, input_html: { class: 'd-none' } %>
                <%= f.submit 'Book a class', class: "teacher-link-a"%>
              <% end %>

          </div>
        <% end %>
      </div>
    </div>

    <div class="col-lg-6" >
      <div class="teacher-left"><!--Map here -->
        <div
          id="map"
          style="height: 100vh;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
        ></div>
      </div>
    </div>
  </div>
</div>